/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControleProduto;
import controle.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloProduto;

/**
 *
 * @author Seie José
 */
public class frmProduto extends javax.swing.JFrame {
    
    ConectaBanco conexao = new ConectaBanco();
    ConectaBanco conecaoPesq  = new ConectaBanco();
    ModeloProduto mod = new ModeloProduto();
    ControleProduto controlo = new ControleProduto();
    
    
    /**
     * Creates new form frmProduto
     */
    public frmProduto() {
        initComponents();
        preecnherCombo();
        preecherTabela("select * from produto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldPrecoCmppra = new javax.swing.JTextField();
        jTextFieldPrecoVenda = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable01 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Produtos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cod:");

        jTextFieldCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCodigo.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Produto: ");

        jTextFieldProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldProduto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldProduto.setEnabled(false);

        jTextFieldPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldQuantidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldQuantidade.setEnabled(false);

        jTextFieldPrecoCmppra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPrecoCmppra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrecoCmppra.setEnabled(false);

        jTextFieldPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPrecoVenda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrecoVenda.setEnabled(false);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButtonSalvarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Preço de Compra:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fornecedor:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Preço de Venda: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Quantidade:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTable01.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable01MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable01);

        jButton1.setText("+");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantidade))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrecoCmppra, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldProduto)
                        .addComponent(jLabel8)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPrecoCmppra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(932, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
       dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new frmFornecedores().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       mod.setFornecedorProduto((String)jComboBox1.getSelectedItem());
       mod.setNomeProduto(jTextFieldProduto.getText());
       mod.setPrecoCompra(Float.parseFloat(jTextFieldPrecoCmppra.getText()));
       mod.setPrecoVenda(Float.parseFloat(jTextFieldPrecoVenda.getText()));
       mod.setQtdProduto(Integer.parseInt(jTextFieldQuantidade.getText()));
       controlo.inserirProduto(mod);
       
       jTextFieldPrecoCmppra.setEnabled(!true);
        jTextFieldPrecoVenda.setEnabled(!true);
        jTextFieldProduto.setEnabled(!true);
        jTextFieldQuantidade.setEnabled(!true);
        jTextFieldPrecoCmppra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldProduto.setText("");
        jTextFieldPesquisa.setText("");
        jButtonEditar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonSalvar.setEnabled(!true);
       preecherTabela("select * from produto");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
//        mod.setPesquisa(jTextFieldPesquisa.getText());
//         ModeloProduto model = controlo.buscaProduto(mod);
//        jTextFieldCodigo.setText(String.valueOf(model.getIdProduto()));
//        jTextFieldProduto.setText(model.getNomeProduto());
//        jTextFieldQuantidade.setText(String.valueOf(model.getQtdProduto()));
//        jTextFieldPrecoCmppra.setText(String.valueOf(model.getPrecoCompra()));
//        jTextFieldPrecoVenda.setText(String.valueOf(model.getPrecoVenda()));
//        jTextFieldPrecoCmppra.setEnabled(true);
//        jTextFieldPrecoVenda.setEnabled(true);
//        jTextFieldProduto.setEnabled(true);
//        jTextFieldQuantidade.setEnabled(true);
//        jButtonEditar.setEnabled(true);
//        jButtonCancelar.setEnabled(true);
//        jButtonExcluir.setEnabled(true);
   //     string nome_produto = ""j+
    //    jComboBox1.setSelectedItem(model.getFornecedorProduto());
        
       preecherTabela("select * from produto where nome_produto like '%"+jTextFieldPesquisa.getText()+"%'");
       
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSalvarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButtonSalvarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarAncestorAdded

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
       mod.setIdProduto(Integer.parseInt(jTextFieldCodigo.getText()));
        mod.setFornecedorProduto((String)jComboBox1.getSelectedItem());
       mod.setNomeProduto(jTextFieldProduto.getText());
       mod.setPrecoCompra(Float.parseFloat(jTextFieldPrecoCmppra.getText()));
       mod.setPrecoVenda(Float.parseFloat(jTextFieldPrecoVenda.getText()));
       mod.setQtdProduto(Integer.parseInt(jTextFieldQuantidade.getText()));
        controlo.editaProduto(mod);
        jTextFieldPrecoCmppra.setEnabled(!true);
        jTextFieldPrecoVenda.setEnabled(!true);
        jTextFieldProduto.setEnabled(!true);
        jTextFieldQuantidade.setEnabled(!true);
        jTextFieldPrecoCmppra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldProduto.setText("");
        jTextFieldPesquisa.setText("");
        jButtonEditar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonSalvar.setEnabled(!true);
        preecherTabela("select * from produto");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        
        mod.setIdProduto(Integer.parseInt(jTextFieldCodigo.getText()));
        controlo.excluirProduto(mod);
        
        jTextFieldPrecoCmppra.setEnabled(!true);
        jTextFieldPrecoVenda.setEnabled(!true);
        jTextFieldProduto.setEnabled(!true);
        jTextFieldQuantidade.setEnabled(!true);
        jTextFieldPrecoCmppra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldPesquisa.setText("");
        jTextFieldProduto.setText("");
         jButtonEditar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonSalvar.setEnabled(!true);
        preecherTabela("select * from produto");
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jTextFieldPrecoCmppra.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        jTextFieldProduto.setEnabled(true);
        jTextFieldQuantidade.setEnabled(true);
        jTextFieldPrecoCmppra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldProduto.setText("");

        jTextFieldCodigo.setText("");
        jTextFieldPesquisa.setText("");
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       jTextFieldPrecoCmppra.setEnabled(!true);
        jTextFieldPrecoVenda.setEnabled(!true);
        jTextFieldProduto.setEnabled(!true);
        jTextFieldQuantidade.setEnabled(!true);
        jTextFieldPrecoCmppra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldPesquisa.setText("");
        jButtonEditar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonSalvar.setEnabled(!true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTable01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable01MouseClicked
        try {
            String nome_produto = ""+jTable01.getValueAt(jTable01.getSelectedRow(), 0);
            conexao.conexao();
            conecaoPesq.conexao();
            conexao.executaSQL("select * from produto where nome_produto='"+nome_produto+"'");
            conexao.rs.first();
            jTextFieldCodigo.setText(String.valueOf(conexao.rs.getInt("id_produto")));
            jTextFieldProduto.setText(conexao.rs.getString("nome_produto"));
            jTextFieldQuantidade.setText(String.valueOf(conexao.rs.getInt("quantidade")));
            jTextFieldPrecoCmppra.setText(String.valueOf(conexao.rs.getFloat("preco_venda")));
            jTextFieldPrecoVenda.setText(String.valueOf(conexao.rs.getFloat("preco_venda")));
            conecaoPesq.executaSQL("select * from fornecedores where id_fornecedor="+conexao.rs.getInt("id_fornecedor"));
            conecaoPesq.rs.first();
            jComboBox1.setSelectedItem(conecaoPesq.rs.getString("nome_fornecedor"));
            
            
         
            jTextFieldPrecoCmppra.setEnabled(true);
            jTextFieldPrecoVenda.setEnabled(true);
            jTextFieldProduto.setEnabled(true);
            jTextFieldQuantidade.setEnabled(true);
            jButtonEditar.setEnabled(true);
            jButtonCancelar.setEnabled(!true);
            jButtonExcluir.setEnabled(true);
            
            conecaoPesq.desconecta();
            conexao.desconecta();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados! Erro: "+ex);
        }
    }//GEN-LAST:event_jTable01MouseClicked

    public void preecnherCombo(){
        conexao.conexao();
        conexao.executaSQL("select * from fornecedores order by nome_fornecedor");
        try{
            conexao.rs.first();
            jComboBox1.removeAllItems();
            do{
                jComboBox1.addItem(conexao.rs.getString("nome_fornecedor"));
            } while(conexao.rs.next());
            conexao.desconecta();
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao preecnher o  combox \nErro:"+e);
        }
    }
    
    public void preecherTabela(String sql){
        ArrayList dados = new ArrayList();
        
        String[] colunas = new String[]{"Nome Produto", "Quantidade", "Preco"};
        conexao.conexao();
        conexao.executaSQL(sql);
        try{
            conexao.rs.first();
            do{
//                dados.add(new Object[]{conn.rs.getInt("id_cidade"),conn.rs.getString("nome_cidades"),conn.rs.getString("sigla_provincia")});
                dados.add(new Object[]{conexao.rs.getString("nome_produto"),conexao.rs.getString("quantidade"),conexao.rs.getString("preco_venda")});
            } while(conexao.rs.next());
        } catch(SQLException e){
        JOptionPane.showMessageDialog(null, "Erro ao preencher a Tabela Cidades ERRO: "+e);}
        
              ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTable01.setModel(modelo);
        jTable01.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable01.getColumnModel().getColumn(0).setResizable(false);
        jTable01.getColumnModel().getColumn(1).setPreferredWidth(500);
        jTable01.getColumnModel().getColumn(1).setResizable(false);
        jTable01.getColumnModel().getColumn(2).setPreferredWidth(350);
        jTable01.getColumnModel().getColumn(2).setResizable(false);
        jTable01.getTableHeader().setReorderingAllowed(false);
        jTable01.setAutoResizeMode(jTable01.AUTO_RESIZE_OFF);
        jTable01.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
       }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable01;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldPrecoCmppra;
    private javax.swing.JTextField jTextFieldPrecoVenda;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
